### ISSUE TITLE
Can't connect with my Hyperboom speaker

### ISSUE THREAD

**Issue by leshokunin** [alessandroaime/homebridge-ueboom#12]
Thanks for creating this plugin! I've been adding a lot of accessories to Homebridge lately and having fun with it.

I've tried adding my UE Hyperboom speaker to Homebridge. I've tried using both the MAC address from my iPhone and my Macbook.
I noticed that the MAC address on the Macbook is written as: xx-xx-xx-xx, and on iPhone as xx:xx:xx:xx.
In the homebridge-ueboom docs, the host MAC is without any punctuation. I've tried all the permutations I could think of of with : or - or nothing addresses. I also called the device Hyperboom, in case that makes a difference (but left the accessory name to the default).

What do you think would make it work? Thanks.

**Comment by alessandroaime** [comment]
Unfortunately I've no idea how it could work with Hyperboom speakers as I don't own any. I would assume that it behaves similarly to the Boom as they both belong to the same "family" but they might have technical differences I'm unaware of that forbid to use this plugin.
