### ISSUE TITLE
Option to use stateless switch

### ISSUE THREAD

**Issue by ScottEgan** [alessandroaime/homebridge-ueboom#5]
I worked at getting an "OFF" command to function but was unsuccessful. In the meantime I think a good addition would be to add the option of using a stateless switch instead of the stateful one. This way the plugin could function like a momentary switch to send the "ON" command. The user could then let the Boom shut off on its own with the auto shut off feature. I'm not very familiar with javascript but I can look at making the change. Thanks

**Comment by alessandroaime** [comment]
I initially set it as stateful as I expected to develop also the OFF feature within days, but as I've been quite busy I haven't been able yet. I could see if is possible to add to `config` a stateful boolean parameter (and having a default value in case nothing is specified) so each user can choose which behaviour have based on their needs until the OFF feature is implemented.

**Comment by alessandroaime** [comment]
Looks like I might be able to do as mentioned above by reassigning the following line

https://github.com/alessandroaime/homebridge-ueboom/blob/e9e6669d59258737fd62b82f5a3e42d4e63464ac/index.js#L14

This could be a possible implementation of the main function:

```javascript
function UEBoomSpeaker(log, config) {
  this.log = log;
  this.name = config.name;
  this.stateful = config.stateful ?? false;
  /*
    I could also use a stronger type check in case the first option throws an error
    (config.stateful === false || config.stateful === true) ? config.stateful : false
  */
  this.reverse = false;
  this.time = 1000;
  this.speaker = config.speaker;
  this.host = config.host;
  this._service = new Service.Switch(this.name);

  ...
}
```

And this is how `config` would look like:

```
{
      "accessory": "UEBoomSpeaker",
      "name": "Bathroom Speaker",
      "stateful": true,
      "speaker": "C0:28:8D:45:28:55",
      "host": "4098ADA356C4"
}
```

In case `stateful` is not declared, then `false` (stateless) would be automatically chosen.

During this week I'll test it and if it works I'll push an update.

**Comment by ScottEgan** [comment]
Awesome, that is exactly what I was thinking. Thanks for considering this!

**Comment by alessandroaime** [comment]
@ScottEgan the [latest release (v1.0.0)](https://github.com/alessandroaime/homebridge-ueboom/releases/tag/v1.0.0) finally introduces the ability to turn the speaker OFF. Unless you're still interested in having a stateless option, I'm going to consider this issue as closed.

**Comment by ScottEgan** [comment]
@alessandroaime Awesome! Yes, we can close.
