### ISSUE TITLE
Integration into Home Assistant

### ISSUE THREAD

**Issue by MartinKuhl** [alessandroaime/homebridge-ueboom#7]
Hi, 
is it possible to integrate this addon into home assistant?
Homebridge is allready included in the homekit plugin:
https://www.home-assistant.io/integrations/homekit

**Comment by alessandroaime** [comment]
Hi Martin, I don't personally use Home Assistant but I can look into how to integrate this package into it.

**Comment by MartinKuhl** [comment]
At the moment I handle this via a very dirty solution and execute a docker excec command into the homebridge docker. 
But so I'm able to start and shutdown the BoomBox.
`docker exec homebridge sh -c "gatttool -i hci0 -b $1 --char-write-req -a 0x0003 -n $2$3"`

$1: mac address ue boombox
$2: mac address device
$3: 01 or 02 for ON or OFF

**Comment by alessandroaime** [comment]
Oh, this is music to my ears!

As soon as I'm home this evening I'll try it out and if it works also for Homebridge I'll update the package and I'll be forever grateful to you.

**Comment by MartinKuhl** [comment]
I used the following modification for homebridge which is working for me:

![image](https://user-images.githubusercontent.com/55736453/94249963-e426b600-ff20-11ea-97f2-efefdacdd603.png)

But your one looks of course better

**Comment by alessandroaime** [comment]
Yours is only a bit more explicit but does exactly the same.

I connected via VPN to my home network and tried to run it and it seems to work, but I'll be 100% when I'll see with my eyes the white led turning off.

**Comment by MartinKuhl** [comment]
Is there any way or command to pair two boomboxes via the gatttool?
That would be a cool feature!

**Comment by alessandroaime** [comment]
I'm not that experienced with `gatttool` to be able to tell, I would have to look into the documentation.

One workaround could be to have two UE Boo speakers in Homebridge/HomeAssistant, both with the same `host`
as in ` "gatttool -i hci0 -b " + this.speaker + " --char-write-req -a 0x0003 -n " + this.host + (on ? "01" : "02")`, and then have an automation in the Home app or in Home Assistant where if one speaker is turned on, to then turn on the other as well and if the host device (iPhone in my case) is able to connect to both then you're good to go.

Otherwise you have either reverse engineer the Boom app or sniff around for commands sent to figure out what happens when two speakers are paired from the official app.

**Comment by MartinKuhl** [comment]
Now what I connect to boomboxes to one host only one box plays the sound. I thought that you could sniff the trafic between app and bombox to get the right command like the command for power ON or Off the device.

**Comment by alessandroaime** [comment]
I updated the above comment saying that most likely the bluetooth protocol stack allows only one active (i.e. streaming music) audio connection per time.

**Comment by alessandroaime** [comment]
My guess is that UE Boom speakers are able to chain between themselves due to some internal hardware that allows that (e.g. a second bluetooth sender/receiver module that allows one speaker to connect master/slave to the other and so forth).

**Comment by alessandroaime** [comment]
With AirPlay 2 enabled speakers is possible to stream to multiple sources. An affordable solution could be to get a couple of IKEA Symfonisk speakers (the ones made in partnership with Sonos) and [adding the ability to use a power-bank as battery supplier](https://www.reddit.com/r/sonos/comments/d18mkh/sonos_ikea_symfonisk_battery_hack_sonos_move/).

**Comment by alessandroaime** [comment]
It works! Thanks @MartinKuhl!!!

I noticed a delay between launching the command from CLI (~3s) and from Homebridge (~15s). I'll investigate what's the reason behind, and then will finally publish `v1.0.0` with the full functionality.

**Comment by alessandroaime** [comment]
@MartinKuhl do you still need the integration into Home Assistant or have you done it yourself? Regardless, I think it would be best to have it in a separate repository rather than mixing it up with Homebridge.

**Comment by MartinKuhl** [comment]
> @MartinKuhl do you still need the integration into Home Assistant or have you done it yourself?
> 
> Closing this as, if there's still the need, I think it would be best to have it as a separate repository rather than mixing it up with Homebridge.

Hi @alessandroaime an integration into home assisstant would be great. At the moment I have to run a homebridge docker and execute commands via docker exec to use the gatttool.

**Comment by alessandroaime** [comment]
I'll reopen the issue as a reminder for myself.
